# Stage 1 model

In [1]:
import pandas as pd
import plotly.express as px

from rich import print

from ambdes import Model, Runner, SimConfig, ArrivalConfig, TimesConfig

## Run model for 100 minutes with log messages

TODO: Convert this into logging tests which compare patient results with record in the vidigi logger.

In [ ]:
class ArrivalConfig:
    """Prepare arrival inputs for the simulation.

    Attributes
    ----------
    arrival_df : pd.DataFrame
        Mean arrival counts by day of week and response category.
    variation_df : pd.DataFrame
        Summary of variation in category proportions across days of the week.
    category_proportions : pd.Series
        Mean proportion of arrivals in each response category across the week.
    nspp_df : pd.DataFrame
        Arrival schedule in the format required by `sim_tools` `NSPPThinning`.

    """

    def __init__(self, arrival_csv, model_type):
        """Initialise ArrivalConfig.

        Parameters
        ----------
        arrival_csv : str | Path
            Path to CSV containing arrival counts by day of week and response
            category.
        model_type : str
            Controls which columns are required and which derived outputs
            are produced.

        """
        if model_type not in ["aggregate", "cycle"]:
            raise ValueError("model_type must be aggregate or cycle.")

        self.arrival_df = pd.read_csv(arrival_csv)

        # Sum conveyed & non-conveyed
        if model_type == "cycle":
            counts = (
                self.arrival_df.groupby(
                    ["day", "category"], observed=False
                )["count"]
                .sum()
                .reset_index()
            )
        else:
            counts = self.arrival_df.copy()

        # Convert to wide format
        wide_df = (
            counts
            .pivot(index="day", columns="category", values="count")
            .reindex(["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"])
        )
        wide_df.columns.name = None

        # Convert to proportion by response category for each day
        proportion_df = wide_df.div(wide_df.sum(axis=1), axis=0)

        # Summarise the variations in proportions by day of week
        self.variation_df = pd.DataFrame(
            {
                "mean": proportion_df.mean(axis=0),
                "min": proportion_df.min(axis=0),
                "max": proportion_df.max(axis=0),
                "range": proportion_df.max(axis=0) - proportion_df.min(axis=0),
                "sd": proportion_df.std(axis=0),
            }
        )

        # Get overall mean proportion by response category
        self.category_proportions = proportion_df.mean(axis=0)

        # Get count of total arrivals per day
        arrivals_per_day = wide_df.sum(axis=1)

        # Convert to format required by sim_tools NSPPThinning class
        # It requires a dataframe with columns "t" (timepoint when arrival
        # rate changes) and "mean_iat" (mean inter-arrival time)
        self.nspp_df = pd.DataFrame(
            {
                "t": range(0, 7 * 1440, 1440),
                "mean_iat": 1440 / arrivals_per_day.values,
            }
        )

        if model_type=="cycle":

In [3]:
import pandas as pd

         area        day category conveyed  count
0   southwest     monday       C1      all     25
1   southwest    tuesday       C1      all     24
2   southwest  wednesday       C1      all     24
3   southwest   thursday       C1      all     24
4   southwest     friday       C1      all     25
5   southwest   saturday       C1      all     28
6   southwest     sunday       C1      all     27
7   southwest     monday       C2      all    310
8   southwest    tuesday       C2      all    295
9   southwest  wednesday       C2      all    295
10  southwest   thursday       C2      all    295
11  southwest     friday       C2      all    305
12  southwest   saturday       C2      all    340
13  southwest     sunday       C2      all    330
14  southwest     monday       C3      all    180
15  southwest    tuesday       C3      all    170
16  southwest  wednesday       C3      all    170
17  southwest   thursday       C3      all    170
18  southwest     friday       C3      all    178
19  southwest   saturday       C3      all    200
20  southwest     sunday       C3      all    195
21  southwest     monday       C4      all     40
22  southwest    tuesday       C4      all     38
23  southwest  wednesday       C4      all     38
24  southwest   thursday       C4      all     38
25  southwest     friday       C4      all     40
26  southwest   saturday       C4      all     45
27  southwest     sunday       C4      all     43

In [73]:
arrival_config = ArrivalConfig(arrival_csv="data/arrivals_conveyed.csv", model_type="cycle")

In [70]:
arrival_config = ArrivalConfig(arrival_csv="data/arrivals.csv", model_type="aggregate")

In [ ]:
arrival_config.arrival_df.groupby(["day", "category"])

          day category  conveyed  count
0      monday       C1      True     20
1      monday       C1     False      5
2     tuesday       C1      True     19
3     tuesday       C1     False      5
4   wednesday       C1      True     19
5   wednesday       C1     False      5
6    thursday       C1      True     19
7    thursday       C1     False      5
8      friday       C1      True     20
9      friday       C1     False      5
10   saturday       C1      True     22
11   saturday       C1     False      6
12     sunday       C1      True     22
13     sunday       C1     False      5
14     monday       C2      True    248
15     monday       C2     False     62
16    tuesday       C2      True    236
17    tuesday       C2     False     59
18  wednesday       C2      True    236
19  wednesday       C2     False     59
20   thursday       C2      True    236
21   thursday       C2     False     59
22     friday       C2      True    244
23     friday       C2     False     61
24   saturday       C2      True    272
25   saturday       C2     False     68
26     sunday       C2      True    264
27     sunday       C2     False     66
28     monday       C3      True    144
29     monday       C3     False     36
30    tuesday       C3      True    136
31    tuesday       C3     False     34
32  wednesday       C3      True    136
33  wednesday       C3     False     34
34   thursday       C3      True    136
35   thursday       C3     False     34
36     friday       C3      True    142
37     friday       C3     False     36
38   saturday       C3      True    160
39   saturday       C3     False     40
40     sunday       C3      True    156
41     sunday       C3     False     39
42     monday       C4      True     32
43     monday       C4     False      8
44    tuesday       C4      True     30
45    tuesday       C4     False      8
46  wednesday       C4      True     30
47  wednesday       C4     False      8
48   thursday       C4      True     30
49   thursday       C4     False      8
50     friday       C4      True     32
51     friday       C4     False      8
52   saturday       C4      True     36
53   saturday       C4     False      9
54     sunday       C4      True     34
55     sunday       C4     False      9

In [46]:
#data = pd.read_csv("data/arrivals.csv")
data = pd.read_csv("data/arrivals_conveyed.csv")

per_day_cat = (
    data.groupby(["day", "category"], observed=False)["count"]
    .sum()
    .reset_index()
)
wide_df = (
    per_day_cat
    .pivot(index="day", columns="category", values="count")
    .reindex(["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"])
)
wide_df.columns.name = None

In [47]:
data

          day category  conveyed  count
0      monday       C1      True     20
1      monday       C1     False      5
2     tuesday       C1      True     19
3     tuesday       C1     False      5
4   wednesday       C1      True     19
5   wednesday       C1     False      5
6    thursday       C1      True     19
7    thursday       C1     False      5
8      friday       C1      True     20
9      friday       C1     False      5
10   saturday       C1      True     22
11   saturday       C1     False      6
12     sunday       C1      True     22
13     sunday       C1     False      5
14     monday       C2      True    248
15     monday       C2     False     62
16    tuesday       C2      True    236
17    tuesday       C2     False     59
18  wednesday       C2      True    236
19  wednesday       C2     False     59
20   thursday       C2      True    236
21   thursday       C2     False     59
22     friday       C2      True    244
23     friday       C2     False     61
24   saturday       C2      True    272
25   saturday       C2     False     68
26     sunday       C2      True    264
27     sunday       C2     False     66
28     monday       C3      True    144
29     monday       C3     False     36
30    tuesday       C3      True    136
31    tuesday       C3     False     34
32  wednesday       C3      True    136
33  wednesday       C3     False     34
34   thursday       C3      True    136
35   thursday       C3     False     34
36     friday       C3      True    142
37     friday       C3     False     36
38   saturday       C3      True    160
39   saturday       C3     False     40
40     sunday       C3      True    156
41     sunday       C3     False     39
42     monday       C4      True     32
43     monday       C4     False      8
44    tuesday       C4      True     30
45    tuesday       C4     False      8
46  wednesday       C4      True     30
47  wednesday       C4     False      8
48   thursday       C4      True     30
49   thursday       C4     False      8
50     friday       C4      True     32
51     friday       C4     False      8
52   saturday       C4      True     36
53   saturday       C4     False      9
54     sunday       C4      True     34
55     sunday       C4     False      9

In [39]:
arrival_config = ArrivalConfig(arrival_csv="data/arrivals_conveyed.csv")

KeyError: 'day'

In [29]:
arrival_config = ArrivalConfig(arrival_csv="data/arrivals.csv")
display(arrival_config.arrival_df)
display(arrival_config.nspp_df)

KeyError: 'day'

In [ ]:
long_df = (
    arrival_config.arrival_df
    .reset_index()                             # bring day index into a column
    .melt(
        id_vars="index",                       # the day column created by reset_index()
        var_name="category",                  # C1..C4
        value_name="count",                   # counts
    )
    .rename(columns={"index": "day"})
)
long_df

In [ ]:
long_df.to_csv("data/arrivals.csv", index=False)

In [ ]:
times_config = TimesConfig(times_csv="data/times.csv")

Inspect this to see if times actually vary by response category:

In [ ]:
times_config.times_df

In [ ]:
times_config.lognormal_config("travel_to_scene")

In [ ]:
config = SimConfig(
    arrival_config=arrival_config,
    times_config=times_config
)
config.n_ambulances = 1

In [ ]:
print(config.dist_config)

In [ ]:
model = Model(run_number=0, config=config)
print(model.dists)

In [ ]:
model.dists["time_to_scene"]["C1"].sample()

In [ ]:
model.run()

In [ ]:
log = model.logger.to_dataframe()

In [ ]:
print(model.patients[0].__dict__)
log[log["entity_id"] == 1]

In [ ]:
print(model.patients[1].__dict__)
log[log["entity_id"] == 2]

## Run model for longer and inspect patient times

In [ ]:
config = SimConfig(
    arrival_config=arrival_config,
    times_config=times_config,
    warm_up_period=0,
    data_collection_period=10080,  # One week
)
model = Model(run_number=0, config=config)
model.run()

In [ ]:
df = pd.DataFrame(
    {
        "response_time": [p.response_time for p in model.patients],
        "category": [p.category for p in model.patients],
    }
)

fig = px.histogram(
    df,
    x="response_time",
    facet_col="category",
    nbins=50,
    category_orders={"category": ["C1", "C2", "C3", "C4"]},
    labels={
        "response_time": "Response time (minutes)",
        "category": "Category",
    },
    title="Distribution of response times by category",
)

# fig.update_yaxes(
#    matches=None,
#    showticklabels=True,
# )
fig.layout.yaxis.title.text = "Number of patients"

fig.show()

In [ ]:
for cat in ["C1", "C2", "C3", "C4"]:
    fig = px.histogram(
        df[df["category"] == cat],
        x="response_time",
        nbins=20,
        title=f"Response times: {cat}",
        labels={"response_time": "Response time (minutes)"},
    )
    fig.update_yaxes(title_text="Number of patients")
    fig.show()

## Average results

In [ ]:
runner = Runner(config)

In [ ]:
results = runner.run_reps()

In [ ]:
results["patients"]

In [ ]:
results["run"]

In [ ]:
results["overall"]

In [ ]:
config.n_ambulances = 1
config.data_collection_period = 50_000
config.log_to_console = False
runner = Runner(config)
results = runner.run_single(run_number=0)

In [ ]:
results["run"]

In [ ]:
results["patients"].head(20)

In [ ]:
results["model"].logger.to_dataframe().head(30)